@startuml
class ApplicationUser {
    + ApplicationUser()
    + ApplicationUser(id:int, name:string, surname:string, direccion:string, telefono:string)
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + Direccion : string <<get>> <<set>>
    + Telefono : string <<get>> <<set>>
}
class "IList`1"<T> {
}
ApplicationUser --> "Resenas<Resena>" "IList`1"
ApplicationUser --> "Compras<Compra>" "IList`1"
ApplicationUser --> "Reposiciones<Reposicion>" "IList`1"
@enduml
