@startuml
class Compra {
    + Compra()
    + Compra(id:int, fechaCompra:DateTime, precioTotal:decimal, codigoDescuento:string)
    + Id : int <<get>> <<set>>
    + FechaCompra : DateTime <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + CodigoDescuento : string? <<get>> <<set>>
}
@enduml
