@startuml
hide methods
!include ApplicationUser.puml
!include Libro.puml
!include Compra.puml
!include Genero.puml
!include CompraItem.puml
!include Editorial.puml
!include MetodoPago.puml
!include PayPal.puml
!include Visa.puml 
!include GooglePay.puml
@enduml