@startuml
class Libro {
    + Libro()
    + Libro(id:int, titulo:string, autor:string, fechaLanzamiento:DateTime, precioCompra:decimal, stock:int)
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + Autor : string <<get>> <<set>>
    + PrecioCompra : decimal <<get>> <<set>>
    + Stock : int <<get>> <<set>>
}
Libro --> "FechaLanzamiento" DateTime
@enduml
