@startuml
class ReposicionItem {
    + ReposicionItem()
    + ReposicionItem(cantidadReposicion:int, libroId:int, reposicionId:int)
    + CantidadReposicion : int <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + ReposicionId : int <<get>> <<set>>
}
ReposicionItem --> "Reposicion" Reposicion
ReposicionItem --> "Libro" Libro
@enduml
