@startuml
class Resena {
    + Resena()
    + Resena(id:int, fechaResena:DateTime, titulo:string)
    + Id : int <<get>> <<set>>
    + FechaResena : DateTime <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + Usuario : ApplicationUser <<get>> <<set>>
    + ResenaItems : IList<ResenaItem> <<get>> <<set>>
}
@enduml
