@startuml
class ResenaItem {
    + ResenaItem()
    + ResenaItem(descripcion:string?, calificacion:int, libroId:int, resenaId:int)
    + Descripcion : string? <<get>> <<set>>
    + Calificacion : int <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + ResenaId : int <<get>> <<set>>
    + Libro : Libro <<get>> <<set>>
    + Resena : Resena <<get>> <<set>>
}
@enduml
