@startuml
class Resena {
    + Resena()
    + Resena(id:int, fechaResena:DateTime, titulo:string)
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
}
class "IList`1"<T> {
}
Resena --> "FechaResena" DateTime
Resena --> "Usuario" ApplicationUser
Resena --> "ResenaItems<ResenaItem>" "IList`1"
@enduml
