@startuml
class Visa {
    + Visa()
    + Visa(numeroTarjeta:string, fechaCaducidad:DateTime)
    + NumeroTarjeta : string <<get>> <<set>>
}
MetodoPago <|-- Visa
Visa --> "FechaCaducidad" DateTime
@enduml
